from diagrams import Cluster, Diagram
from diagrams.aws.network import VPC, PublicSubnet, PrivateSubnet
from diagrams.aws.security import Guardduty
from diagrams.aws.compute import Lambda

with Diagram("ASCA Architecture", show=False):
    guardduty = Guardduty("Threat Detection")
    with Cluster("Sweden-Prod-VPC"):
        with Cluster("Public Layer"):
            public_net = PublicSubnet("NAT Gateway")
        with Cluster("Private Layer"):
            private_net = PrivateSubnet("App Server")
            remedy_func = Lambda("Auto-Isolation")
            
    guardduty >> remedy_func >> private_net
